window.NATIVE_CATALOG = {
  scene: {
    id: "scn-tech-software-dev",
    name: "软件研发",
    industry: "科技互联网",
  },
  talent: [
    {
      id: "psn-tech-sample-ai-engineer",
      name: "示例·AI增强型软件工程师",
      type: "human",
      typeLabel: "真人 · 样例",
      role: "软件研发实践者",
      scene: "scn-tech-software-dev",
      sceneName: "软件研发",
      fit: "high",
      contrib: "A",
      why: "场景锚点完整，能力绑定 programming；非正式名人榜。",
      sample: true,
    },
    {
      id: "psn-tech-sample-coding-persona",
      name: "示例·仓库编程分身",
      type: "digital-persona",
      typeLabel: "数字人格 · 非真人",
      role: "产品内编程人格",
      scene: "scn-tech-software-dev",
      sceneName: "软件研发",
      fit: "high",
      contrib: "B",
      why: "已披露运营方 Anthropic。不可充当真人达人投放。",
      sample: true,
    },
    {
      id: "aim-tech-sd-feature",
      name: "研发交付 AI Man",
      type: "ai-man",
      typeLabel: "数字专才 · 非达人榜",
      role: "功能交付数字专才",
      scene: "scn-tech-software-dev",
      sceneName: "软件研发",
      fit: "high",
      contrib: "S",
      why: "绑定功能开发解决方案。审查必须人签。",
      sample: false,
    },
  ],
  enterprises: [
    {
      id: "brd-github",
      name: "GitHub",
      type: "公司",
      scene: "scn-tech-software-dev",
      sceneName: "软件研发",
      fit: "high",
      contrib: "S",
      partner: "开发者生态与 Copilot 联合方案",
      why: "基础设施 + 编程助手产品，本场景可建联。",
    },
    {
      id: "brd-anthropic",
      name: "Anthropic",
      type: "实验室",
      scene: "scn-tech-software-dev",
      sceneName: "软件研发",
      fit: "high",
      contrib: "A",
      partner: "模型与代码审查能力",
      why: "Claude 覆盖仓库级理解与审查。",
    },
    {
      id: "brd-openai",
      name: "OpenAI",
      type: "实验室",
      scene: "scn-tech-software-dev",
      sceneName: "软件研发",
      fit: "medium",
      contrib: "A",
      partner: "通用对话能力",
      why: "可合作但不是本场景第一供给。",
    },
  ],
  solution: {
    id: "sol-tech-sd-feature-delivery",
    name: "功能开发场景解决方案",
    aiMan: "研发交付 AI Man",
    checkpoints: ["需求拆解", "方案确认", "代码审查"],
  },
};
